project:
  type: website

website:
  title: "Bhargav Kowshik"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Learning"
        href: learning/index.qmd
      - text: "Blog"
        href: blog/index.qmd
    right:
      - text: "About"
        href: about/index.qmd
  page-footer: "Built with ❤️ from Bengaluru, India"

format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto  # re-render only when source changes.

resources:
  - CNAME
