project:
  type: website

website:
  title: "Bhargav Kowshik"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: learning.qmd
      - href: blog.qmd
    right:
      - href: about.qmd
  page-footer: "Built with ❤️ from Bengaluru, India"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

resources:
  - CNAME